### ISSUE TITLE
How to navigate from a redux-action ?

### ISSUE THREAD

**Issue by taipa-ibl** [daose/react-native-template#1]
I see you setup react-navigation with redux, but in your template, i don't know how to navigate in a redux-actions like react-native-router-flux ( just import a action and use it).
Thank you.

**Comment by daose** [comment]
You can `import { NavigationActions } from 'react-navigation'`, and then if you have `dispatch`, you can do

```javascript
dispatch(NavigationActions.navigate({ routeName: 'Route' });
```

So if you're in a saga

```javascript
yield put(NavigationActions.navigate({ routeName: 'Route' }); // import put from redux-saga/effects
```

I updated `sagas/login.js`.

There's a lot more you can do with it as well, you can see the available actions at [NavigationActions.js](https://github.com/react-community/react-navigation/blob/master/src/NavigationActions.js)

**Comment by taipa-ibl** [comment]
Thank you !
